sources:
  - arg: keyword that will be auto-completed in the command. lowecase, single word.
    scene: name of the scene in OBS. Case sensitive.
    desc: description to show in discord autocomplete.
layouts:
  - arg: keyword that will be auto-completed in the command. lowecase, single word.
    scene: name of the scene in OBS. Case sensitive.
    desc: description to show in discord autocomplete.
    slots:
      - bigbox
      - mid
slots:
  argument: OBS name. example below
  bigbox: S_BIGBOX
